# Generated by Django 4.2.4 on 2023-09-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Kliento nr.')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Kliento vardas')),
                ('customer_surname', models.CharField(max_length=200, verbose_name='Kliento pavardė')),
                ('customer_phone', models.CharField(max_length=200, verbose_name='Kliento tel. nr.')),
                ('customer_email', models.EmailField(max_length=200, verbose_name='Kliento el. paštas')),
                ('customer_address', models.CharField(default='-', max_length=200, verbose_name='Kliento adresas')),
                ('customer_city', models.CharField(default='-', max_length=200, verbose_name='Kliento miestas')),
                ('customer_postal_code', models.CharField(default='-', max_length=200, verbose_name='Kliento pašto kodas ')),
                ('customer_notes', models.CharField(default='-', max_length=200, verbose_name='Pastabos')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mokėjimo nr.')),
                ('payment_date', models.DateField(verbose_name='Mokėjimo data')),
                ('payment_time', models.TimeField(verbose_name='Mokėjimo laikas')),
                ('payment_type', models.CharField(choices=[('Banko pavedimu', 'Banko pavedimu'), ('Grynais', 'Grynais'), ('Kortele', 'Kortele')], max_length=20, verbose_name='Mokėjimo būdas')),
                ('payment_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma')),
                ('payment_status', models.CharField(max_length=20, verbose_name='Būsena')),
                ('payment_notes', models.CharField(max_length=200, verbose_name='Pastabos')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'Mokėjimas',
                'verbose_name_plural': 'Mokėjimai',
            },
        ),
    ]
