# Generated by Django 4.2.4 on 2023-09-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('j_types', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Užsakymo nr.')),
                ('order_date', models.DateField(help_text='Pasirinkite užsakymo datą', verbose_name='Užsakymo Data')),
                ('order_time', models.TimeField(help_text='Pasirinkite užsakymo laiką', verbose_name='Užsakymo Laikas')),
                ('order_total', models.DecimalField(decimal_places=2, default=1.0, help_text='Suma (koreaguojama)', max_digits=10, verbose_name='Suma')),
                ('order_status', models.CharField(choices=[('Priimtas', 'Priimtas'), ('Atšauktas', 'Atšauktas'), ('Vykdomas', 'Vykdomas'), ('Atliktas', 'Atliktas'), ('Pranešimas išsiųstas', 'Pranešimas išsiųstas'), ('Apmokėtas', 'Apmokėtas'), ('Atsiimtas', 'Atsiimtas'), ('Užbaigtas', 'Užbaigtas')], help_text='Pasirinkite užsakymo būseną', max_length=20, verbose_name='Užsakymo Būsena')),
                ('order_notes', models.CharField(blank=True, default='-', max_length=200, verbose_name='Pastabos')),
                ('package_count', models.IntegerField(default=1, help_text='Gamyba nurodo pakuotės kiekį', verbose_name='Pakuotės Kiekis')),
                ('package_count2', models.IntegerField(blank=True, default=0, help_text='Gamyba nurodo pakuotės kiekį', null=True, verbose_name='Pakuotės Kiekis 2')),
                ('sum_for_package', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma (koreaguojama)', max_digits=10, verbose_name='Suma už pakuotę')),
                ('service_count', models.IntegerField(blank=True, default=0, help_text='Paslaugų kiekis', null=True, verbose_name='Kiekis')),
                ('b_name', models.ManyToManyField(blank=True, help_text='pasirinkite vieną ar kelias uogas', to='j_types.juiceberries', verbose_name='Uogos')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Klientas')),
                ('f_name', models.ManyToManyField(blank=True, help_text='pasirinkite vieną ar kelis vaisius', to='j_types.juicefruits', verbose_name='Vaisiai')),
                ('j_name', models.ManyToManyField(help_text='Sulčių tipas', to='j_types.juicetypes', verbose_name='Sultys')),
                ('package_name', models.ManyToManyField(help_text='Pasirinkite pakuotės tipą', to='j_types.package', verbose_name='Pakuotės tipas')),
                ('package_name2', models.ManyToManyField(blank=True, help_text='Pasirinkite antrą pakuotės tipą', related_name='package_name2', to='j_types.package', verbose_name='Pakuotės tipas 2')),
                ('service_name', models.ManyToManyField(blank=True, help_text='Pasirinkite vieną ar kelias paslaugas', to='j_types.services', verbose_name='Paslauga')),
                ('v_name', models.ManyToManyField(blank=True, help_text='pasirinkite vieną ar kelias daržoves', to='j_types.juicevegetables', verbose_name='Daržovės')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'ordering': ['order_id'],
            },
        ),
    ]
